version: '3.8'
services:
  backend:
    build:
      context: quizer-backend
      dockerfile: /Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/quizer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: quizer
      MYSQL_USER: shubham
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: 
      context: quizer-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    image: app:react
    container_name: react_container
    command: npm start
volumes:
  db-data: